-- Seed sample data for local development (includes all 72 melakartas)
-- Run: npx wrangler d1 execute carnatic-music-db --local --file=scripts/seed.sql

-- 72 Melakarta ragas
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Kanakangi', 'kanakangi', 'S R1 G1 M1 P D1 N1 S', 'S N1 D1 P M1 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 1. Kanakangi.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Ratnangi', 'ratnangi', 'S R1 G1 M1 P D1 N2 S', 'S N2 D1 P M1 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 2. Ratnangi.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Ganamurti', 'ganamurti', 'S R1 G1 M1 P D1 N3 S', 'S N3 D1 P M1 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 3. Ganamurti.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Vanaspati', 'vanaspati', 'S R1 G1 M1 P D2 N2 S', 'S N2 D2 P M1 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 4. Vanaspati.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Manavati', 'manavati', 'S R1 G1 M1 P D2 N3 S', 'S N3 D2 P M1 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 5. Manavati.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Tanarupi', 'tanarupi', 'S R1 G1 M1 P D3 N3 S', 'S N3 D3 P M1 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 6. Tanarupi.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Senavati', 'senavati', 'S R1 G2 M1 P D1 N1 S', 'S N1 D1 P M1 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 7. Senavati.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Hanumatodi', 'hanumatodi', 'S R1 G2 M1 P D1 N2 S', 'S N2 D1 P M1 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 8. Hanumatodi.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Dhenuka', 'dhenuka', 'S R1 G2 M1 P D1 N3 S', 'S N3 D1 P M1 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 9. Dhenuka.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Natakapriya', 'natakapriya', 'S R1 G2 M1 P D2 N2 S', 'S N2 D2 P M1 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 10. Natakapriya.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Kokilapriya', 'kokilapriya', 'S R1 G2 M1 P D2 N3 S', 'S N3 D2 P M1 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 11. Kokilapriya.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Rupavati', 'rupavati', 'S R1 G2 M1 P D3 N3 S', 'S N3 D3 P M1 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 12. Rupavati.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Gayakapriya', 'gayakapriya', 'S R1 G3 M1 P D1 N1 S', 'S N1 D1 P M1 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 13. Gayakapriya.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Vakulabharanam', 'vakulabharanam', 'S R1 G3 M1 P D1 N2 S', 'S N2 D1 P M1 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 14. Vakulabharanam.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Mayamalavagowla', 'mayamalavagowla', 'S R1 G3 M1 P D1 N3 S', 'S N3 D1 P M1 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 15. Mayamalavagowla.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Chakravakam', 'chakravakam', 'S R1 G3 M1 P D2 N2 S', 'S N2 D2 P M1 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 16. Chakravakam.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Suryakantam', 'suryakantam', 'S R1 G3 M1 P D2 N3 S', 'S N3 D2 P M1 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 17. Suryakantam.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Hatakambari', 'hatakambari', 'S R1 G3 M1 P D3 N3 S', 'S N3 D3 P M1 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 18. Hatakambari.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Jhankaradhvani', 'jhankaradhvani', 'S R2 G2 M1 P D1 N1 S', 'S N1 D1 P M1 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 19. Jhankaradhvani.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Natabhairavi', 'natabhairavi', 'S R2 G2 M1 P D1 N2 S', 'S N2 D1 P M1 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 20. Natabhairavi.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Kiravani', 'kiravani', 'S R2 G2 M1 P D1 N3 S', 'S N3 D1 P M1 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 21. Kiravani.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Kharaharapriya', 'kharaharapriya', 'S R2 G2 M1 P D2 N2 S', 'S N2 D2 P M1 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 22. Kharaharapriya.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Gourimanohari', 'gourimanohari', 'S R2 G2 M1 P D2 N3 S', 'S N3 D2 P M1 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 23. Gourimanohari.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Varunapriya', 'varunapriya', 'S R2 G2 M1 P D3 N3 S', 'S N3 D3 P M1 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 24. Varunapriya.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Mararanjani', 'mararanjani', 'S R2 G3 M1 P D1 N1 S', 'S N1 D1 P M1 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 25. Mararanjani.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Charukesi', 'charukesi', 'S R2 G3 M1 P D1 N2 S', 'S N2 D1 P M1 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 26. Charukesi.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Sarasangi', 'sarasangi', 'S R2 G3 M1 P D1 N3 S', 'S N3 D1 P M1 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 27. Sarasangi.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Harikambhoji', 'harikambhoji', 'S R2 G3 M1 P D2 N2 S', 'S N2 D2 P M1 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 28. Harikambhoji.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Dheerasankarabharanam', 'dheerasankarabharanam', 'S R2 G3 M1 P D2 N3 S', 'S N3 D2 P M1 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 29. Dheerasankarabharanam.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Naganandini', 'naganandini', 'S R2 G3 M1 P D3 N3 S', 'S N3 D3 P M1 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 30. Naganandini.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Yagapriya', 'yagapriya', 'S R3 G3 M1 P D1 N1 S', 'S N1 D1 P M1 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 31. Yagapriya.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Ragavardhini', 'ragavardhini', 'S R3 G3 M1 P D1 N2 S', 'S N2 D1 P M1 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 32. Ragavardhini.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Gangeyabhushani', 'gangeyabhushani', 'S R3 G3 M1 P D1 N3 S', 'S N3 D1 P M1 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 33. Gangeyabhushani.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Vagadheeswari', 'vagadheeswari', 'S R3 G3 M1 P D2 N2 S', 'S N2 D2 P M1 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 34. Vagadheeswari.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Shulini', 'shulini', 'S R3 G3 M1 P D2 N3 S', 'S N3 D2 P M1 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 35. Shulini.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Chalanata', 'chalanata', 'S R3 G3 M1 P D3 N3 S', 'S N3 D3 P M1 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 36. Chalanata.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Salagam', 'salagam', 'S R1 G1 M2 P D1 N1 S', 'S N1 D1 P M2 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 37. Salagam.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Jalarnavam', 'jalarnavam', 'S R1 G1 M2 P D1 N2 S', 'S N2 D1 P M2 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 38. Jalarnavam.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Jhalavarali', 'jhalavarali', 'S R1 G1 M2 P D1 N3 S', 'S N3 D1 P M2 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 39. Jhalavarali.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Navaneetam', 'navaneetam', 'S R1 G1 M2 P D2 N2 S', 'S N2 D2 P M2 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 40. Navaneetam.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Pavani', 'pavani', 'S R1 G1 M2 P D2 N3 S', 'S N3 D2 P M2 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 41. Pavani.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Raghupriya', 'raghupriya', 'S R1 G1 M2 P D3 N3 S', 'S N3 D3 P M2 G1 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 42. Raghupriya.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Gavambhodi', 'gavambhodi', 'S R1 G2 M2 P D1 N1 S', 'S N1 D1 P M2 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 43. Gavambhodi.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Bhavapriya', 'bhavapriya', 'S R1 G2 M2 P D1 N2 S', 'S N2 D1 P M2 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 44. Bhavapriya.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Shubhapantuvarali', 'shubhapantuvarali', 'S R1 G2 M2 P D1 N3 S', 'S N3 D1 P M2 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 45. Shubhapantuvarali.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Shadvidamargini', 'shadvidamargini', 'S R1 G2 M2 P D2 N2 S', 'S N2 D2 P M2 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 46. Shadvidamargini.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Suvarnangi', 'suvarnangi', 'S R1 G2 M2 P D2 N3 S', 'S N3 D2 P M2 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 47. Suvarnangi.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Divyamani', 'divyamani', 'S R1 G2 M2 P D3 N3 S', 'S N3 D3 P M2 G2 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 48. Divyamani.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Dhavalambari', 'dhavalambari', 'S R1 G3 M2 P D1 N1 S', 'S N1 D1 P M2 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 49. Dhavalambari.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Namanarayani', 'namanarayani', 'S R1 G3 M2 P D1 N2 S', 'S N2 D1 P M2 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 50. Namanarayani.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Kamavardhini', 'kamavardhini', 'S R1 G3 M2 P D1 N3 S', 'S N3 D1 P M2 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 51. Kamavardhini.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Ramapriya', 'ramapriya', 'S R1 G3 M2 P D2 N2 S', 'S N2 D2 P M2 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 52. Ramapriya.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Gamanashrama', 'gamanashrama', 'S R1 G3 M2 P D2 N3 S', 'S N3 D2 P M2 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 53. Gamanashrama.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Vishwambari', 'vishwambari', 'S R1 G3 M2 P D3 N3 S', 'S N3 D3 P M2 G3 R1 S', 'melakarta', 'evening', 'various', 'Melakarta 54. Vishwambari.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Shamalangi', 'shamalangi', 'S R2 G2 M2 P D1 N1 S', 'S N1 D1 P M2 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 55. Shamalangi.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Shanmukhapriya', 'shanmukhapriya', 'S R2 G2 M2 P D1 N2 S', 'S N2 D1 P M2 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 56. Shanmukhapriya.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Simhendramadhyamam', 'simhendramadhyamam', 'S R2 G2 M2 P D1 N3 S', 'S N3 D1 P M2 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 57. Simhendramadhyamam.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Hemavati', 'hemavati', 'S R2 G2 M2 P D2 N2 S', 'S N2 D2 P M2 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 58. Hemavati.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Dharmavati', 'dharmavati', 'S R2 G2 M2 P D2 N3 S', 'S N3 D2 P M2 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 59. Dharmavati.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Neetimati', 'neetimati', 'S R2 G2 M2 P D3 N3 S', 'S N3 D3 P M2 G2 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 60. Neetimati.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Kantamani', 'kantamani', 'S R2 G3 M2 P D1 N1 S', 'S N1 D1 P M2 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 61. Kantamani.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Rishabhapriya', 'rishabhapriya', 'S R2 G3 M2 P D1 N2 S', 'S N2 D1 P M2 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 62. Rishabhapriya.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Latangi', 'latangi', 'S R2 G3 M2 P D1 N3 S', 'S N3 D1 P M2 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 63. Latangi.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Vachaspati', 'vachaspati', 'S R2 G3 M2 P D2 N2 S', 'S N2 D2 P M2 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 64. Vachaspati.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Mechakalyani', 'mechakalyani', 'S R2 G3 M2 P D2 N3 S', 'S N3 D2 P M2 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 65. Mechakalyani.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Chitrambari', 'chitrambari', 'S R2 G3 M2 P D3 N3 S', 'S N3 D3 P M2 G3 R2 S', 'melakarta', 'evening', 'various', 'Melakarta 66. Chitrambari.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Sucharitra', 'sucharitra', 'S R3 G3 M2 P D1 N1 S', 'S N1 D1 P M2 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 67. Sucharitra.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Jyotiswarupini', 'jyotiswarupini', 'S R3 G3 M2 P D1 N2 S', 'S N2 D1 P M2 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 68. Jyotiswarupini.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Dhatuvardhani', 'dhatuvardhani', 'S R3 G3 M2 P D1 N3 S', 'S N3 D1 P M2 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 69. Dhatuvardhani.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Nasikabhushani', 'nasikabhushani', 'S R3 G3 M2 P D2 N2 S', 'S N2 D2 P M2 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 70. Nasikabhushani.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Kosalam', 'kosalam', 'S R3 G3 M2 P D2 N3 S', 'S N3 D2 P M2 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 71. Kosalam.', '[]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Rasikapriya', 'rasikapriya', 'S R3 G3 M2 P D3 N3 S', 'S N3 D3 P M2 G3 R3 S', 'melakarta', 'evening', 'various', 'Melakarta 72. Rasikapriya.', '[]', 0, 0, unixepoch(), unixepoch());
-- Common janya ragas (so compositions referencing them resolve)
INSERT OR IGNORE INTO ragas (name, slug, melakarta, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Shankarabharanam', 'shankarabharanam', 'Dheerasankarabharanam', 'S R G M P D N S', 'S N D P M G R S', 'janya', 'evening', 'devotional', 'The 29th melakarta (Dheerasankarabharanam), equivalent to the major scale. Known for its grandeur.', '["M P D S","S R G M P"]', 0, 0, unixepoch(), unixepoch());
INSERT OR IGNORE INTO ragas (name, slug, melakarta, arohanam, avarohanam, type, prahar, rasa, description, characteristic_phrases, average_rating, total_ratings, created_at, updated_at) VALUES ('Mohanam', 'mohanam', 'Harikambhoji', 'S R G P D S', 'S D P G R S', 'janya', 'evening', 'serene', 'A pentatonic janya of Harikambhoji. Pleasant and soothing.', '["S R G P","P D S"]', 0, 0, unixepoch(), unixepoch());

INSERT OR IGNORE INTO composers (name, slug, period, biography, language, created_at) VALUES
('Thyagaraja', 'thyagaraja', '1767-1847', 'One of the Trinity of Carnatic music. Composed thousands of devotional songs in Telugu.', 'Telugu', unixepoch()),
('Muthuswami Dikshitar', 'muthuswami-dikshitar', '1775-1835', 'One of the Trinity. Known for Sanskrit kritis and complex raga usage.', 'Sanskrit', unixepoch());

INSERT OR IGNORE INTO compositions (title, slug, composer_id, raga_id, tala, type, language, lyrics_original, lyrics_transliterated, lyrics_translated, difficulty, created_at, updated_at) VALUES
('Endaro Mahanubhavulu', 'endaro-mahanubhavulu', 1, (SELECT id FROM ragas WHERE slug = 'shankarabharanam' LIMIT 1), 'Adi', 'kriti', 'telugu', 'Endaro mahanubhavulu...', 'Endaro mahanubhavulu andariki vandanamulu...', 'Salutations to all the great souls...', 'intermediate', unixepoch(), unixepoch());

INSERT OR IGNORE INTO resources (title, slug, type, category, difficulty, description, "order", created_at, updated_at) VALUES
('Sarali Varisai 1', 'sarali-varisai-1', 'exercise', 'sarali', 'beginner', 'Basic ascending and descending scale practice.', 1, unixepoch(), unixepoch()),
('Janta Varisai 1', 'janta-varisai-1', 'exercise', 'janta', 'beginner', 'Double notes practice.', 2, unixepoch(), unixepoch());
